### ISSUE TITLE
Inicializar a comunicação com sensores de veículo.

### ISSUE THREAD

**Issue by LeoVPires** [JardiNaHora/sistema-embarcado#2]

**Comment by pauloguilherme0** [comment]
- A comunicação com o sistema embarcado deu-se com sucesso.
- Com uma certa frequência o sistema embarcado apresenta um problema em relação à comunicação do microcontrolador com o módulo GPS e isso inibe a aquisição dos dados.
- É necessário tratar desse problema em atualizações posteriores.
